config/routes.rb
Rails.application.routes.draw do
  root 'directory/alumni#index'
  devise_for :gmails, controllers: { registrations: 'gmails/registrations', omniauth_callbacks:'gmails/omniauth_callbacks' }
  devise_scope :gmail do
    get 'gmails/sign_in', to: 'gmails/sessions#new', as: :new_gmail_session
    get 'gmails/sign_out', to: 'gmails/sessions#destroy', as: :destroy_gmail_session
    get 'gmails/choose_role', to: 'gmails/registrations#choose_role', as: :choose_role_registration
    post 'gmails', to: 'gmails/registrations#create', as: :create_gmail
  end

  namespace :directory do
    resources :alumni, only: [:index, :show]
    resources :students, only: [:index, :show]
  end
  
  get 'user_guide', to: 'user_guide#index', as: 'user_guide'
  
  resources :alumni, except: [:index] do
    member do
      post "claim_experiences"
      delete "remove_experience", to: "alumni#remove_experience"
      post 'claim_professions'
      delete 'remove_profession'
      get :complete_profile
    end
  end

  resources :students, except: [:index] do
    member do 
      post "claim_experiences"
      delete "remove_experiences", to: "students#remove_experience"
    end
  end

  get 'directory/students', to: 'students#index', as: 'student_directory'

  namespace :admin do
    resources :alumni
    resources :users do
      post :give_admin, on: :member
    end
    resources :experiences
    resources :professions, only: [:index, :create, :destroy]
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'  # This creates /admin/dashboard
    get 'dashboard/:id', to: 'dashboard#show', as: 'dashboard_show'
    get 'logs', to: 'logs#index', as: 'logs'
  end

  resources :change_logs, only: [:index]
  resources :experiences
  resources :alumnus_experiences, only: [:edit, :update, :destroy]
  resources :experiences
  resources :professions
  resources :alumnus_professions, only: [:edit, :update, :destroy]
  resources :student_experiences, only: [:edit, :update, :destroy]
end

app/models/experience.rb
class Experience < ApplicationRecord
  include Loggable
  has_many :alumnus_experiences, dependent: :destroy
  has_many :alumni, through: :alumnus_experiences

  has_many :student_experiences, dependent: :destroy
  has_many :students, through: :student_experiences

  validates :title, presence: true
  validates :experience_type, presence: true
end

app/controllers/admin/experiences_controller.rb
# app/controllers/admin/experiences_controller.rb
class Admin::ExperiencesController < ApplicationController
    layout 'admin'
    #before_action :authenticate_admin!
    
    def index
      @experiences = Experience.all.order(created_at: :desc)
    end
    
    def create
      @experience = Experience.new(experience_params)
      
      if @experience.save
        redirect_to admin_experiences_path, notice: 'Experience was successfully created.'
      else
        redirect_to admin_experiences_path, alert: 'Failed to create experience.'
      end
    end
    
    def show
      @experience = Experience.find(params[:id])
    end
    
    def edit
      @experience = Experience.find(params[:id])
    end
    
    def update
      @experience = Experience.find(params[:id])
      if @experience.update(experience_params)
        redirect_to admin_experiences_path, notice: 'Experience was successfully updated.'
      else
        render :edit
      end
    end
    
    def destroy
      @experience = Experience.find(params[:id])
      @experience.destroy
      redirect_to admin_experiences_path, notice: 'Experience was successfully deleted.'
    end
    
    private
    
    def experience_params
      params.require(:experience).permit(:title, :experience_type)
    end
    
    # def authenticate_admin!
    #   # Check if user is logged in and is an admin
    #   unless current_gmail&.user.isAdmin
    #     flash[:alert] S= "You must be an admin to access this page."
    #     redirect_to root_path
    #   end
    # end
  end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[show edit update destroy]

  def index
    @experiences = Experience.all.order(created_at: :desc)
  end

  def show; end

  def new
    @experience = Experience.new
  end

  def create
    Rails.logger.debug "PARAMS RECEIVED: #{params.inspect}"
    @experience = Experience.new(experience_params)
    
    # used by both alumnus and students 
    owner = if params[:experience][:alumnus_id].present?
      Alumnus.find_by(id: params[:experience][:alumnus_id])
    elsif params[:experience][:student_id].present?
      Student.find_by(id: params[:experience][:student_id])
    end
    

    if @experience.save
      owner.experiences << @experience if owner
      respond_to do |format|
        if owner
          format.html { redirect_to edit_polymorphic_path(owner), notice: "Experience added!" }
        else
          format.html { redirect_to experiences_path, notice: "Experience added!" }
        end
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.js { render json: { errors: @experience.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    if @experience.update(experience_params)
      redirect_to @experience, notice: "Experience was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @experience.destroy
    redirect_to experiences_url, notice: "Experience was successfully deleted."
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:title, :experience_type)
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<div id="<%= dom_id experience %>">
  <p>
    <strong>Title:</strong>
    <%= experience.title %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= experience.experience_type %>
  </p>

</div>

app/views/experiences/_form.html.erb
<%= form_with(model: experience) do |form| %>
  <% if experience.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :experience_type, style: "display: block" %>
    <%= form.text_field :experience_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/create.js.erb
if ("<%= j @experience.persisted? %>" === "true") {
    document.getElementById("experience_modal").style.display = "none";
  
    const newExperience = document.createElement("li");
    newExperience.innerHTML = `
      <strong><%= j @experience.title %> (<%= j @experience.experience_type %>)</strong>  
      <br>
      <p><%= j @experience.description %></p>
      <a href="#" class="remove_experience" data-id="<%= j @experience.id %>">Remove</a>
    `;
  
    document.getElementById("claimed_experiences").appendChild(newExperience);
  } else {
    alert("Error: <%= j @experience.errors.full_messages.join(', ') %>");
  }
  

app/views/experiences/edit.html.erb
<% content_for :title, "Editing experience" %>

<h1>Editing experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Show this experience", @experience %> |
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Experiences" %>

<h1>Experiences</h1>

<div id="experiences">
  <% @experiences.each do |experience| %>
    <%= render experience %>
    <p>
      <%= link_to "Show this experience", experience %>
    </p>
  <% end %>
</div>

<%= link_to "New experience", new_experience_path %>

app/views/experiences/new.html.erb
<% content_for :title, "New experience" %>

<h1>New experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @experience %>

<div>
  <%= link_to "Edit this experience", edit_experience_path(@experience) %> |
  <%= link_to "Back to experiences", experiences_path %>

  <%= button_to "Destroy this experience", @experience, method: :delete %>
</div>